# Generated by Django 6.0.3 on 2026-03-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('profile_role', models.CharField(max_length=20, verbose_name='Rol objetivo')),
                ('notebook_url', models.URLField(verbose_name='URL NotebookLM')),
                ('description', models.TextField(blank=True)),
                ('use_cases', models.TextField(blank=True, verbose_name='Casos de uso (uno por línea)')),
                ('image_name', models.CharField(max_length=100, verbose_name='Nombre de imagen')),
                ('establishment', models.CharField(blank=True, max_length=20, verbose_name='Establecimiento (opcional)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Consulta')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(editable=False, verbose_name='Plazo de respuesta (24h)')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('respondida', 'Respondida'), ('vencida', 'Vencida')], default='pendiente', max_length=15)),
                ('answer', models.TextField(blank=True, verbose_name='Respuesta')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Consulta IA',
                'verbose_name_plural': 'Consultas IA',
                'ordering': ['deadline'],
            },
        ),
    ]
