# Generated by Django 6.0.3 on 2026-03-05 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquery',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiquery',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='ai_modules.aiassistant'),
        ),
        migrations.AddField(
            model_name='aiquery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
