# Generated by Django 6.0.3 on 2026-03-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquery',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ai_queries/', verbose_name='Archivo adjunto'),
        ),
    ]
