# Generated by Django 6.0.2 on 2026-04-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0003_aiquery_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistant',
            name='context_text',
            field=models.TextField(blank=True, verbose_name='Contexto Extraído (RAG)'),
        ),
        migrations.AddField(
            model_name='aiassistant',
            name='system_instruction',
            field=models.TextField(blank=True, verbose_name='Instrucción de Sistema (Prompt)'),
        ),
        migrations.CreateModel(
            name='AIKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del documento')),
                ('file', models.FileField(upload_to='ai_knowledge/', verbose_name='Archivo PDF')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Texto extraído')),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='ai_modules.aiassistant')),
            ],
        ),
    ]
