# Generated by Django 6.0.2 on 2026-04-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0004_aiassistant_context_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquery',
            name='ai_suggestion',
            field=models.TextField(blank=True, verbose_name='Sugerencia de la IA (RAG)'),
        ),
    ]
