# Generated by Django 6.0.2 on 2026-04-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0006_aiassistant_is_chat_enabled_aichatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIKnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido del fragmento')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadatos (Establecimiento, Rol, Doc)')),
                ('chunk_id', models.CharField(max_length=100, unique=True, verbose_name='ID Único del fragmento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_modules.aiassistant')),
            ],
            options={
                'verbose_name': 'Fragmento de Conocimiento',
                'verbose_name_plural': 'Fragmentos de Conocimiento',
            },
        ),
    ]
