# Generated by Django 6.0.2 on 2026-04-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0007_aiknowledgechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiknowledgechunk',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del documento fuente'),
        ),
        migrations.AddField(
            model_name='aiknowledgechunk',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Índice de secuencia en el documento'),
        ),
    ]
