# Generated by Django 6.0.2 on 2026-04-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0008_aiknowledgechunk_document_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiknowledgechunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='Vector Embedding (OpenAI)'),
        ),
    ]
