# Generated by Django 6.0.2 on 2026-04-13 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0009_aiknowledgechunk_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Caso')),
                ('sustento', models.TextField(verbose_name='Sustento Normativo (Sección A)')),
                ('ruta', models.TextField(verbose_name='Hoja de Ruta (Sección B)')),
                ('checklist', models.TextField(verbose_name='Checklist (Sección C)')),
                ('descargos', models.TextField(blank=True, verbose_name='Redacción de Descargos')),
                ('status', models.CharField(choices=[('abierto', 'Abierto (En Proceso)'), ('cerrado', 'Cerrado (Resuelto)')], default='abierto', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_modules.aiassistant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caso Normativo',
                'verbose_name_plural': 'Repositorio de Casos',
                'ordering': ['-created_at'],
            },
        ),
    ]
