# Generated by Django 6.0.2 on 2026-04-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0010_aicase'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicase',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observaciones del Usuario'),
        ),
    ]
