# Generated by Django 6.0.2 on 2026-04-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0012_caseobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicase',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
