# Generated by Django 6.0.2 on 2026-04-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0013_aicase_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicase',
            name='user_query',
            field=models.TextField(blank=True, verbose_name='Consulta Original del Usuario'),
        ),
    ]
