# Generated by Django 6.0.2 on 2026-04-23 03:10

from django.db import migrations


def delete_ghosts(apps, schema_editor):
    AIAssistant = apps.get_model('ai_modules', 'AIAssistant')
    AIQuery = apps.get_model('ai_modules', 'AIQuery')
    AIChatMessage = apps.get_model('ai_modules', 'AIChatMessage')
    AICase = apps.get_model('ai_modules', 'AICase')

    temuco_slugs = ['director-temuco', 'utp-temuco', 'representante-temuco', 'inspector-temuco', 'convivencia-temuco']
    
    # Intentar buscar un target para no perder datos
    target = AIAssistant.objects.filter(slug='director-temuco').first()
    if not target:
        return

    # Borrar todo lo que no sea Temuco
    ghosts = AIAssistant.objects.exclude(slug__in=temuco_slugs)
    for old in ghosts:
        # Reasignar relaciones
        AIQuery.objects.filter(assistant=old).update(assistant=target)
        AIChatMessage.objects.filter(assistant=old).update(assistant=target)
        AICase.objects.filter(assistant=old).update(assistant=target)
        old.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0014_aicase_user_query'),
    ]

    operations = [
        migrations.RunPython(delete_ghosts),
    ]
