# Generated by Django 6.0.2 on 2026-04-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0015_delete_ghost_assistants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiassistant',
            name='notebook_url',
        ),
    ]
