# Generated by Django 6.0.2 on 2026-04-29 12:07

from django.db import migrations

def ensure_director_admin_permissions(apps, schema_editor):
    try:
        # Usamos el modelo de la app users
        User = apps.get_model('users', 'User')
        u = User.objects.filter(username='director.admin').first()
        if u:
            u.is_staff = False
            u.role = 'DIRECTOR'
            u.save()
    except Exception:
        pass # Evitar que falle si el modelo no está disponible en este punto

class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0019_apply_ai_protocol'),
    ]

    operations = [
        migrations.RunPython(ensure_director_admin_permissions),
    ]
