# Generated by Django 6.0.3 on 2026-03-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.CharField(choices=[('TEMUCO', 'Temuco'), ('LAUTARO', 'Lautaro'), ('RENAICO', 'Renaico'), ('SANTIAGO', 'Santiago'), ('FLORIDA', 'Florida'), ('IMPERIAL', 'Imperial'), ('ERCILLA', 'Ercilla'), ('ARAUCO', 'Arauco'), ('ANGOL', 'Angol'), ('RED', 'Equipo Red Congregacional')], max_length=20, verbose_name='Establecimiento')),
                ('profile_role', models.CharField(blank=True, choices=[('REPRESENTANTE', 'Representante Legal'), ('UTP', 'Unidad Técnica Pedagógica'), ('DIRECTOR', 'Director/a'), ('INSPECTOR', 'Inspector/a General'), ('CONVIVENCIA', 'Encargado/a Convivencia Escolar'), ('RED', 'Equipo Red')], max_length=20, verbose_name='Rol responsable')),
                ('title', models.CharField(max_length=200, verbose_name='Meta')),
                ('description', models.TextField(blank=True)),
                ('target_value', models.FloatField(verbose_name='Valor meta')),
                ('current_value', models.FloatField(default=0, verbose_name='Valor actual')),
                ('measurement_unit', models.CharField(max_length=50, verbose_name='Unidad')),
                ('deadline', models.DateField(verbose_name='Plazo')),
                ('status', models.CharField(choices=[('en_progreso', 'En Progreso'), ('cumplido', 'Cumplido'), ('en_riesgo', 'En Riesgo'), ('vencido', 'Vencido')], default='en_progreso', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meta de Mejora',
                'verbose_name_plural': 'Metas de Mejora',
                'ordering': ['deadline', 'establishment'],
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('plazo_mineduc', 'Plazo MINEDUC'), ('brecha_normativa', 'Brecha Normativa'), ('documento_vencido', 'Documento Vencido'), ('meta_en_riesgo', 'Meta en Riesgo'), ('consulta_ia_vencida', 'Consulta IA Vencida'), ('reunion_cuota', 'Cuota de Reuniones Alcanzada')], max_length=25, verbose_name='Tipo de Alerta')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('affected_establishments', models.JSONField(default=list, verbose_name='Establecimientos afectados')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('related_object_info', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Alerta de Riesgo',
                'verbose_name_plural': 'Alertas de Riesgo',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
