# Generated by Django 6.0.3 on 2026-03-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvement_cycle', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementgoal',
            name='subvention_type',
            field=models.CharField(choices=[('SEP', 'SEP'), ('PIE', 'PIE'), ('MANTENCION', 'Mantención'), ('PRO_RETENCION', 'Pro-Retención'), ('OTRO', 'Otro')], default='SEP', max_length=20, verbose_name='Tipo de Subvención'),
        ),
        migrations.AlterField(
            model_name='improvementgoal',
            name='description',
            field=models.TextField(blank=True, verbose_name='Resumen/Descripción'),
        ),
        migrations.AlterField(
            model_name='improvementgoal',
            name='establishment',
            field=models.CharField(choices=[('TEMUCO', 'Temuco'), ('LAUTARO', 'Lautaro'), ('RENAICO', 'Renaico'), ('SANTIAGO', 'Santiago'), ('IMPERIAL', 'Imperial'), ('ERCILLA', 'Ercilla'), ('ARAUCO', 'Arauco'), ('ANGOL', 'Angol'), ('RED', 'Equipo Red Congregacional')], max_length=20, verbose_name='Establecimiento'),
        ),
    ]
