# Generated by Django 6.0.3 on 2026-03-18 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvement_cycle', '0003_improvementgoal_subvention_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Acción/Hito')),
                ('description', models.TextField(blank=True, verbose_name='Descripción de la acción')),
                ('deadline', models.DateField(verbose_name='Plazo de la acción')),
                ('weight', models.FloatField(default=1.0, verbose_name='Peso/Importancia (1-100)')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='improvement_cycle.improvementgoal')),
                ('responsible', models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Acción de Mejora',
                'verbose_name_plural': 'Acciones de Mejora',
                'ordering': ['deadline', 'created_at'],
            },
        ),
    ]
