# Generated by Django 6.0.3 on 2026-03-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvement_cycle', '0004_improvementaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementaction',
            name='evidence',
            field=models.TextField(blank=True, verbose_name='Evidencia / Observaciones'),
        ),
    ]
