# Generated by Django 6.0.2 on 2026-04-21 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvement_cycle', '0005_improvementaction_evidence'),
        ('meetings', '0005_meetingbooking_acta_meetingbooking_acuerdos_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementgoal',
            name='associated_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_cycles', to='meetings.meetingbooking'),
        ),
        migrations.AddField(
            model_name='improvementgoal',
            name='indicators',
            field=models.JSONField(blank=True, default=list, verbose_name='Indicadores de Logro (IA)'),
        ),
        migrations.AddField(
            model_name='improvementgoal',
            name='is_meeting_cycle',
            field=models.BooleanField(default=False, verbose_name='Es ciclo de reunión'),
        ),
        migrations.AddField(
            model_name='improvementgoal',
            name='process_route',
            field=models.JSONField(blank=True, default=list, verbose_name='Ruta de Procesos (IA)'),
        ),
        migrations.AddField(
            model_name='improvementgoal',
            name='strategic_objectives',
            field=models.TextField(blank=True, verbose_name='Objetivos Estratégicos'),
        ),
    ]
