# Generated by Django 6.0.2 on 2026-04-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvement_cycle', '0006_improvementgoal_associated_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementgoal',
            name='is_generating',
            field=models.BooleanField(default=False, verbose_name='IA Redactando'),
        ),
        migrations.AlterField(
            model_name='improvementgoal',
            name='strategic_objectives',
            field=models.JSONField(blank=True, default=list, verbose_name='Objetivos Estratégicos'),
        ),
        migrations.AlterField(
            model_name='improvementgoal',
            name='subvention_type',
            field=models.CharField(choices=[('SEP', 'SEP'), ('PIE', 'PIE'), ('MANTENCION', 'Mantención'), ('PRO_RETENCION', 'Pro-Retención'), ('NO_CORRESPONDE', 'No corresponde'), ('OTRO', 'Otro')], default='SEP', max_length=20, verbose_name='Tipo de Subvención'),
        ),
    ]
