# Generated by Django 6.0.2 on 2026-04-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvement_cycle', '0007_improvementgoal_is_generating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementgoal',
            name='edit_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Historial de Ediciones'),
        ),
    ]
