# Generated by Django 6.0.2 on 2026-05-05 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvement_cycle', '0008_improvementgoal_edit_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completado el'),
        ),
        migrations.AddField(
            model_name='improvementaction',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_actions', to=settings.AUTH_USER_MODEL, verbose_name='Completado por'),
        ),
    ]
