# Generated by Django 6.0.2 on 2026-05-06 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(verbose_name='Orden global (1-30)')),
                ('enunciado', models.TextField(verbose_name='Enunciado de la pregunta')),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, '⭐ Inicial'), (2, '⭐⭐ Intermedio'), (3, '⭐⭐⭐ Avanzado')], verbose_name='Nivel de dificultad')),
                ('habilidad', models.CharField(max_length=200, verbose_name='Habilidad que evalúa')),
                ('habilidad_justificacion', models.TextField(blank=True, verbose_name='Justificación habilidad')),
                ('nivel_justificacion', models.TextField(blank=True, verbose_name='Justificación nivel')),
                ('alternativa_correcta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Alternativa correcta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('texto', models.TextField(verbose_name='Texto de la alternativa')),
                ('es_correcta', models.BooleanField(default=False)),
                ('justificacion', models.TextField(blank=True, verbose_name='Justificación (para pauta)')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='simce.pregunta')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'ordering': ['letra'],
                'unique_together': {('pregunta', 'letra')},
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('asignatura', models.CharField(choices=[('lenguaje', 'Lenguaje y Comunicación'), ('matematica', 'Matemática'), ('ciencias', 'Ciencias Naturales'), ('historia', 'Historia, Geografía y Cs. Sociales')], max_length=20)),
                ('curso', models.CharField(choices=[('4B', '4° Básico'), ('6B', '6° Básico'), ('8B', '8° Básico'), ('2M', '2° Medio')], max_length=3)),
                ('anio', models.PositiveSmallIntegerField(default=2026, verbose_name='Año')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada')], default='borrador', max_length=12)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('aprobada_en', models.DateTimeField(blank=True, null=True)),
                ('rubrica_ok', models.BooleanField(default=False, verbose_name='Rúbrica superada')),
                ('rubrica_log', models.JSONField(default=dict, verbose_name='Detalle rúbrica')),
                ('prompt_usado', models.TextField(blank=True, verbose_name='Prompt de generación')),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_simce', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prueba SIMCE',
                'verbose_name_plural': 'Pruebas SIMCE',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='SesionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('establecimiento', models.CharField(max_length=20, verbose_name='Establecimiento')),
                ('rbd', models.CharField(blank=True, max_length=10, verbose_name='RBD')),
                ('curso', models.CharField(choices=[('4B', '4° Básico'), ('6B', '6° Básico'), ('8B', '8° Básico'), ('2M', '2° Medio')], max_length=3)),
                ('letra_curso', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('puntaje_bruto', models.PositiveSmallIntegerField(default=0)),
                ('porcentaje_logro', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('puntaje_simce', models.PositiveSmallIntegerField(default=0)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='simce.prueba')),
            ],
            options={
                'verbose_name': 'Sesión estudiante',
                'verbose_name_plural': 'Sesiones estudiantes',
                'ordering': ['-iniciada_en'],
            },
        ),
        migrations.CreateModel(
            name='TextoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(verbose_name='Orden (1-6)')),
                ('tipo_textual', models.CharField(choices=[('cuento', 'Cuento'), ('fabula', 'Fábula'), ('noticia', 'Noticia'), ('reportaje', 'Reportaje'), ('articulo_cient', 'Artículo Científico'), ('receta', 'Receta'), ('instructivo', 'Manual / Instructivo'), ('afiche', 'Afiche Publicitario'), ('soneto', 'Soneto'), ('oda', 'Oda'), ('discontinuo', 'Texto Informativo Discontinuo'), ('infografia', 'Infografía'), ('carta_formal', 'Carta Formal'), ('carta_director', 'Carta al Director'), ('carta_informal', 'Carta Informal')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(verbose_name='Contenido del texto')),
                ('char_count', models.PositiveIntegerField(default=0, verbose_name='Caracteres sin espacios')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='simce.prueba')),
            ],
            options={
                'verbose_name': 'Texto',
                'verbose_name_plural': 'Textos',
                'ordering': ['orden'],
                'unique_together': {('prueba', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='texto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='simce.textoprueba'),
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondida_en', models.DateTimeField(auto_now=True)),
                ('alternativa_elegida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simce.alternativa')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simce.pregunta')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='simce.sesionestudiante')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'unique_together': {('sesion', 'pregunta')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together={('texto', 'orden')},
        ),
    ]
