# Generated by Django 6.0.2 on 2026-05-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='pista_1',
            field=models.TextField(blank=True, verbose_name='Pista 1 (tras 1er error)'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='pista_2',
            field=models.TextField(blank=True, verbose_name='Pista 2 (tras 2do error)'),
        ),
        migrations.AddField(
            model_name='respuestaestudiante',
            name='intentos',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Intentos usados'),
        ),
        migrations.AddField(
            model_name='respuestaestudiante',
            name='puntaje_obtenido',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Puntaje (0-4)'),
        ),
    ]
