# Generated by Django 6.0.2 on 2026-05-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simce', '0002_pistas_y_reintentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionestudiante',
            name='modo',
            field=models.CharField(choices=[('simce', 'Estilo SIMCE (1 pt, sin pistas)'), ('pistas', 'Con pistas e intentos (4-3-2-0)')], default='simce', max_length=8, verbose_name='Modo'),
        ),
    ]
