# Generated by Django 6.0.3 on 2026-03-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Acuerdo')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Plazo')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('cumplido', 'Cumplido'), ('vencido', 'Vencido')], default='pendiente', max_length=15)),
            ],
            options={
                'verbose_name': 'Acuerdo',
                'verbose_name_plural': 'Acuerdos',
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asistencia',
            },
        ),
        migrations.CreateModel(
            name='MeetingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='Fecha y hora')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duración (min)')),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('activa', 'Activa'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='programada', max_length=15)),
                ('agenda', models.TextField(blank=True, verbose_name='Agenda')),
                ('month_year', models.CharField(editable=False, max_length=7, verbose_name='Mes-Año (YYYY-MM)')),
            ],
            options={
                'verbose_name': 'Reserva de Reunión',
                'verbose_name_plural': 'Reservas de Reuniones',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Documento')),
                ('file', models.FileField(upload_to='meetings/docs/%Y/%m/', verbose_name='Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento de Reunión',
            },
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Sala')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug Jitsi')),
                ('description', models.TextField(blank=True)),
                ('allowed_roles', models.JSONField(blank=True, default=list, verbose_name='Roles permitidos')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Reuniones ilimitadas')),
            ],
            options={
                'verbose_name': 'Sala de Reunión',
                'verbose_name_plural': 'Salas de Reunión',
            },
        ),
    ]
