# Generated by Django 6.0.3 on 2026-03-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingbooking',
            name='recording_url',
            field=models.URLField(blank=True, help_text='Enlace al video de la reunión', null=True, verbose_name='URL de Grabación'),
        ),
    ]
