# Generated by Django 6.0.2 on 2026-04-06 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_red', '0002_initial'),
        ('meetings', '0003_meetingbooking_recording_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingbooking',
            name='calendar_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_booking', to='calendar_red.calendarevent'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='daily_identifier',
            field=models.CharField(blank=True, help_text='ID al final de la URL de Daily', max_length=100),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='room_type',
            field=models.CharField(choices=[('jitsi', 'Jitsi Meet (Clásico)'), ('daily', 'Daily.co (Nuevo)')], default='jitsi', max_length=10),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='target_establishment',
            field=models.CharField(blank=True, max_length=20, verbose_name='Establecimiento vinculado'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='target_role',
            field=models.CharField(blank=True, max_length=20, verbose_name='Rol vinculado'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, verbose_name='Roles permitidos (Manual)'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug Identificador'),
        ),
    ]
