# Generated by Django 6.0.2 on 2026-04-20 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meetingbooking_calendar_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingbooking',
            name='acta',
            field=models.TextField(blank=True, verbose_name='Acta de Reunión (DeepSeek)'),
        ),
        migrations.AddField(
            model_name='meetingbooking',
            name='acuerdos_text',
            field=models.TextField(blank=True, verbose_name='Acuerdos Extraídos'),
        ),
        migrations.AddField(
            model_name='meetingbooking',
            name='processing_status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=15, verbose_name='Estado de Procesamiento IA'),
        ),
        migrations.AddField(
            model_name='meetingbooking',
            name='recording_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID de Grabación'),
        ),
        migrations.AddField(
            model_name='meetingbooking',
            name='transcript',
            field=models.TextField(blank=True, verbose_name='Transcripción (Whisper)'),
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre/Identificador')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_participants', to='meetings.meetingbooking')),
            ],
            options={
                'verbose_name': 'Participante Detectado',
                'verbose_name_plural': 'Participantes Detectados',
            },
        ),
    ]
