# Generated by Django 6.0.2 on 2026-04-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meetingbooking_acta_meetingbooking_acuerdos_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingbooking',
            name='recording_url',
            field=models.CharField(blank=True, help_text='Enlace al video o identificador de Daily', max_length=500, null=True, verbose_name='URL de Grabación'),
        ),
    ]
