# Generated by Django 6.0.2 on 2026-04-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_alter_meetingbooking_recording_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingbooking',
            name='processing_status',
            field=models.CharField(choices=[('sin_grabacion', 'Sin Grabación'), ('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='sin_grabacion', max_length=15, verbose_name='Estado de Procesamiento IA'),
        ),
        migrations.AlterField(
            model_name='meetingbooking',
            name='recording_url',
            field=models.CharField(blank=True, help_text='Enlace al video o identificador de Daily (daily_id:xxx)', max_length=500, null=True, verbose_name='URL de Grabación'),
        ),
    ]
