# Generated by Django 6.0.2 on 2026-04-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_add_sin_grabacion_status_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='room_type',
            field=models.CharField(choices=[('daily', 'Daily.co (Videollamadas)')], default='daily', max_length=10),
        ),
    ]
