# Generated by Django 6.0.2 on 2026-05-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_add_guest_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingbooking',
            name='recording_r2_url',
            field=models.URLField(blank=True, help_text='Enlace permanente al video en Cloudflare R2', max_length=1000, null=True, verbose_name='URL de Grabación en R2'),
        ),
    ]
