# Generated by Django 6.0.3 on 2026-03-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título del Formulario')),
                ('description', models.TextField(blank=True)),
                ('form_url', models.URLField(verbose_name='Link al Formulario (Google Forms)')),
                ('results_url', models.URLField(blank=True, verbose_name='Link a Resultados (PDF)')),
                ('session_type', models.CharField(choices=[('presencial', 'Reunión Presencial'), ('virtual', 'Reunión Virtual')], default='presencial', max_length=15)),
                ('applied_at', models.DateField(blank=True, null=True, verbose_name='Fecha de aplicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formulario de Evaluación',
                'verbose_name_plural': 'Formularios de Evaluación',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('file', models.FileField(blank=True, null=True, upload_to='evidencia/%Y/%m/')),
                ('external_url', models.URLField(blank=True, verbose_name='URL externa (si aplica)')),
                ('category', models.CharField(choices=[('presentacion', 'Presentación'), ('acta', 'Acta'), ('foto', 'Fotografía'), ('otro', 'Otro')], default='otro', max_length=15)),
                ('session_type', models.CharField(choices=[('presencial', 'Reunión Presencial'), ('virtual', 'Reunión Virtual')], default='presencial', max_length=15)),
                ('session_date', models.DateField(blank=True, null=True, verbose_name='Fecha de la reunión')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento de Evidencia',
                'ordering': ['-session_date'],
            },
        ),
    ]
