# Generated by Django 6.0.3 on 2026-03-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('event_date', models.DateField(verbose_name='Fecha')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('event_type', models.CharField(choices=[('mineduc', 'Plazo MINEDUC'), ('supereduc', 'Superintendencia de Educación'), ('agencia', 'Agencia de Calidad'), ('congregacional', 'Congregacional'), ('interno', 'Interno EE')], default='interno', max_length=20, verbose_name='Tipo')),
                ('applies_to_roles', models.JSONField(blank=True, default=list, verbose_name='Roles')),
                ('applies_to_establishments', models.JSONField(blank=True, default=list, verbose_name='Establecimientos')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Crítico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento del Calendario',
                'verbose_name_plural': 'Eventos del Calendario',
                'ordering': ['event_date', 'event_time'],
            },
        ),
    ]
