# Generated by Django 6.0.3 on 2026-03-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('circular', 'Nueva Circular'), ('mensaje', 'Nuevo Mensaje'), ('ai_respuesta', 'Respuesta IA Lista'), ('ai_vencida', 'Consulta IA Vencida'), ('reunion', 'Recordatorio de Reunión'), ('alerta', 'Alerta de Riesgo'), ('documento', 'Nuevo Documento')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='URL de destino')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
